-- ═══════════════════════════════════════════════════════════════════════
-- Brick & Clay — Historical Sales Import from Closing Balance Excel
-- June 2026 (12 days)
-- cash_sales = Cash Sale
-- online_sales = Card + UPI
-- aggregator_sales = ZoGoId + Zomato + Swiggy + SwiggyDin + EazyDiner
-- Run in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════════════

DO $$
DECLARE
  v_owner_id uuid;
BEGIN
  SELECT id INTO v_owner_id FROM public.profiles WHERE role = 'owner' LIMIT 1;
  IF v_owner_id IS NULL THEN
    RAISE EXCEPTION 'Owner profile not found';
  END IF;

  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-01', v_owner_id, 3782, 13162, 11888, 0, 0, 0, 0, 'Opening: ₹505 | Closing: ₹1651 | Card: ₹0 | UPI: ₹13162 | ZoGoId: ₹1254 | Zomato: ₹6653 | Swiggy: ₹2620 | SwiggyDin: ₹838 | EazyDiner: ₹523') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-02', v_owner_id, 849, 9240, 13524, 0, 0, 0, 0, 'Opening: ₹1651 | Closing: ₹1652 | Card: ₹1433 | UPI: ₹7807 | ZoGoId: ₹3392 | Zomato: ₹7900 | Swiggy: ₹911 | SwiggyDin: ₹1321 | EazyDiner: ₹0') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-03', v_owner_id, 513, 10749, 20815, 0, 0, 0, 0, 'Opening: ₹1652 | Closing: ₹779 | Card: ₹860 | UPI: ₹9889 | ZoGoId: ₹4891 | Zomato: ₹7880 | Swiggy: ₹4380 | SwiggyDin: ₹3067 | EazyDiner: ₹597') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-04', v_owner_id, 1000, 4536, 22654, 0, 0, 0, 0, 'Opening: ₹779 | Closing: ₹1719 | Card: ₹0 | UPI: ₹4536 | ZoGoId: ₹0 | Zomato: ₹8039 | Swiggy: ₹10828 | SwiggyDin: ₹3787 | EazyDiner: ₹0') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-05', v_owner_id, 2943, 5086, 14160, 0, 0, 0, 0, 'Opening: ₹1719 | Closing: ₹880 | Card: ₹1203 | UPI: ₹3883 | ZoGoId: ₹6166 | Zomato: ₹1033 | Swiggy: ₹4751 | SwiggyDin: ₹2210 | EazyDiner: ₹0') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-06', v_owner_id, 3875, 17612, 18357, 0, 0, 0, 0, 'Opening: ₹880 | Closing: ₹2115 | Card: ₹2451 | UPI: ₹15161 | ZoGoId: ₹3860 | Zomato: ₹5798 | Swiggy: ₹4608 | SwiggyDin: ₹1985 | EazyDiner: ₹2106') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-07', v_owner_id, 1929, 12354, 22847, 0, 0, 0, 0, 'Opening: ₹2115 | Closing: ₹2802 | Card: ₹628 | UPI: ₹11726 | ZoGoId: ₹3598 | Zomato: ₹5761 | Swiggy: ₹9972 | SwiggyDin: ₹2448 | EazyDiner: ₹1068') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-08', v_owner_id, 1726, 2280, 12229, 0, 0, 0, 0, 'Opening: ₹2802 | Closing: ₹1218 | Card: ₹0 | UPI: ₹2280 | ZoGoId: ₹2908 | Zomato: ₹1550 | Swiggy: ₹2964 | SwiggyDin: ₹3319 | EazyDiner: ₹1488') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-09', v_owner_id, 1928, 13393, 9210, 0, 0, 0, 0, 'Opening: ₹1218 | Closing: ₹1160 | Card: ₹0 | UPI: ₹13393 | ZoGoId: ₹5915 | Zomato: ₹0 | Swiggy: ₹0 | SwiggyDin: ₹2866 | EazyDiner: ₹429') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-10', v_owner_id, 4516, 4308, 5274, 0, 0, 0, 0, 'Opening: ₹1160 | Closing: ₹2426 | Card: ₹0 | UPI: ₹4308 | ZoGoId: ₹1925 | Zomato: ₹0 | Swiggy: ₹0 | SwiggyDin: ₹2438 | EazyDiner: ₹911') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-11', v_owner_id, 1790, 5981, 22510, 0, 0, 0, 0, 'Opening: ₹2426 | Closing: ₹1250 | Card: ₹0 | UPI: ₹5981 | ZoGoId: ₹3829 | Zomato: ₹3386 | Swiggy: ₹13338 | SwiggyDin: ₹1130 | EazyDiner: ₹827') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;
  INSERT INTO public.daily_sales (date, submitted_by, cash_sales, online_sales, aggregator_sales, total_bills, discount_amount, complimentary_count, complimentary_value, notes) VALUES ('2026-06-12', v_owner_id, 366, 7607, 18314, 0, 0, 0, 0, 'Opening: ₹1250 | Closing: ₹1000 | Card: ₹1025 | UPI: ₹6582 | ZoGoId: ₹1833 | Zomato: ₹7011 | Swiggy: ₹8342 | SwiggyDin: ₹670 | EazyDiner: ₹458') ON CONFLICT (date) DO UPDATE SET cash_sales = EXCLUDED.cash_sales, online_sales = EXCLUDED.online_sales, aggregator_sales = EXCLUDED.aggregator_sales, notes = EXCLUDED.notes, submitted_by = EXCLUDED.submitted_by;

  RAISE NOTICE 'Done — imported 12 days of sales data';
END $$;